"""
master_data_loader.py

Master Data Loader for the Smart Manufacturing Intelligence Platform (SMIP).

This module loads all manufacturing master data generated by SMIP v1.0.
The loaded datasets provide the Digital Twin context used to enrich
streaming manufacturing events.

Author:
Sumanth Vempalle 

Version:
2.0.0
"""

from __future__ import annotations

import logging

import pandas as pd

from generator.configs.paths import (
    PRODUCTS_PATH,
    MACHINES_PATH,
    OPERATIONS_PATH,
    OPERATORS_PATH,
    TOOLS_PATH,
    STATIONS_PATH,
    PRODUCTION_LINES_PATH,
    PRODUCTION_HALLS_PATH,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)-8s %(message)s",
)

logger = logging.getLogger(__name__)


class MasterDataLoader:
    """
    Loads all manufacturing master datasets.

    These datasets represent the Digital Twin of the factory and
    are used to enrich manufacturing events before they are
    published to the streaming pipeline.
    """

    def __init__(self) -> None:

        self.products: pd.DataFrame | None = None

        self.machines: pd.DataFrame | None = None

        self.operations: pd.DataFrame | None = None

        self.operators: pd.DataFrame | None = None

        self.tools: pd.DataFrame | None = None

        self.stations: pd.DataFrame | None = None

        self.production_lines: pd.DataFrame | None = None

        self.production_halls: pd.DataFrame | None = None

    # ============================================================
    # Public API
    # ============================================================

    def load(self) -> None:
        """
        Load all master datasets.
        """

        logger.info("========================================")
        logger.info("Loading SMIP Master Data")
        logger.info("========================================")

        self.products = self._load_csv(PRODUCTS_PATH)

        self.machines = self._load_csv(MACHINES_PATH)

        self.operations = self._load_csv(OPERATIONS_PATH)

        self.operators = self._load_csv(OPERATORS_PATH)

        self.tools = self._load_csv(TOOLS_PATH)

        self.stations = self._load_csv(STATIONS_PATH)

        self.production_lines = self._load_csv(
            PRODUCTION_LINES_PATH
        )

        self.production_halls = self._load_csv(
            PRODUCTION_HALLS_PATH
        )

        logger.info("Master data successfully loaded.")

    # ============================================================
    # Private Methods
    # ============================================================

    @staticmethod
    def _load_csv(path) -> pd.DataFrame:
        """
        Load a master dataset.
        """

        df = pd.read_csv(path)

        logger.info(
            "Loaded %-25s %8d rows",
            path.name,
            len(df),
        )

        return df

    # ============================================================
    # Summary
    # ============================================================

    def summary(self) -> None:
        """
        Print dataset statistics.
        """

        logger.info("========================================")
        logger.info("Master Dataset Summary")
        logger.info("========================================")

        datasets = {

            "Products": self.products,

            "Machines": self.machines,

            "Operations": self.operations,

            "Operators": self.operators,

            "Tools": self.tools,

            "Stations": self.stations,

            "Production Lines": self.production_lines,

            "Production Halls": self.production_halls,

        }

        for name, df in datasets.items():

            rows = 0 if df is None else len(df)

            logger.info(
                "%-20s %8d",
                name,
                rows,
            )

        logger.info("========================================")