"""
transactional_loader.py

Transactional Data Loader for the Smart Manufacturing Intelligence Platform (SMIP).

This module loads transactional manufacturing datasets generated by
SMIP v1.0 and provides them to the streaming event producer.

Author:
Sumanth Vempalle + ChatGPT

Version:
2.0.0
"""

from __future__ import annotations

import logging

import pandas as pd

from generator.configs.paths import (
    WORK_ORDERS_PATH,
    PRODUCTION_EXECUTIONS_PATH,
    SERIAL_NUMBERS_PATH,
    PRESS_OPERATIONS_PATH,
    TEST_RESULTS_PATH,
    MATERIAL_SCANS_PATH,
    PACKAGING_PATH,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)-8s %(message)s",
)

logger = logging.getLogger(__name__)


class TransactionalLoader:
    """
    Loads all transactional datasets generated by SMIP v1.0.

    The loaded datasets are used by the streaming event producer
    to publish manufacturing events in chronological order.
    """

    def __init__(self) -> None:

        self.work_orders: pd.DataFrame | None = None

        self.executions: pd.DataFrame | None = None

        self.serial_numbers: pd.DataFrame | None = None

        self.press_operations: pd.DataFrame | None = None

        self.test_results: pd.DataFrame | None = None

        self.material_scans: pd.DataFrame | None = None

        self.packaging: pd.DataFrame | None = None

    # ============================================================
    # Public API
    # ============================================================

    def load(self) -> None:
        """
        Load all transactional datasets.
        """

        logger.info("========================================")
        logger.info("Loading SMIP Transactional Datasets")
        logger.info("========================================")

        self.work_orders = self._load_csv(
            WORK_ORDERS_PATH,
            parse_dates=[
                "planned_start",
                "planned_finish",
            ],
        )

        self.executions = self._load_csv(
            PRODUCTION_EXECUTIONS_PATH,
            parse_dates=[
                "execution_start",
                "execution_end",
            ],
        )

        self.serial_numbers = self._load_csv(
            SERIAL_NUMBERS_PATH,
            parse_dates=[
                "manufacturing_date",
            ],
        )

        self.press_operations = self._load_csv(
            PRESS_OPERATIONS_PATH,
            parse_dates=[
                "operation_start",
                "operation_end",
            ],
        )

        self.test_results = self._load_csv(
            TEST_RESULTS_PATH,
            parse_dates=[
                "start_time",
                "end_time",
            ],
        )

        self.material_scans = self._load_csv(
            MATERIAL_SCANS_PATH,
            parse_dates=[
                "scan_timestamp",
            ],
        )

        self.packaging = self._load_csv(
            PACKAGING_PATH,
            parse_dates=[
                "packaging_start",
                "packaging_end",
            ],
        )

        logger.info("All transactional datasets loaded successfully.")

    # ============================================================
    # Private Methods
    # ============================================================

    @staticmethod
    def _load_csv(
        path,
        parse_dates: list[str] | None = None,
    ) -> pd.DataFrame:
        """
        Load a CSV dataset.
        """

        df = pd.read_csv(
            path,
            parse_dates=parse_dates,
        )

        logger.info(
            "Loaded %-25s %8d rows",
            path.name,
            len(df),
        )

        return df


    # ============================================================
    # Dataset Getters
    # ============================================================

    def get_work_orders(
        self,
    ) -> pd.DataFrame:
        """
        Return Work Orders.
        """

        return self.work_orders

    def get_executions(
        self,
    ) -> pd.DataFrame:
        """
        Return Production Executions.
        """

        return self.executions

    def get_serial_numbers(
        self,
    ) -> pd.DataFrame:
        """
        Return Serial Numbers.
        """

        return self.serial_numbers

    def get_press_operations(
        self,
    ) -> pd.DataFrame:
        """
        Return Manufacturing Operations.
        """

        return self.press_operations

    def get_operations(
        self,
    ) -> pd.DataFrame:
        """
        Return Manufacturing Operations using the canonical name.
        """

        return self.get_press_operations()

    def get_quality_results(
        self,
    ) -> pd.DataFrame:
        """
        Return Quality Test Results.
        """

        return self.test_results

    def get_material_events(
        self,
    ) -> pd.DataFrame:
        """
        Return Material Scan records.
        """

        return self.material_scans

    def get_packaging_records(
        self,
    ) -> pd.DataFrame:
        """
        Return Packaging records.
        """

        return self.packaging

    def get_packaging(
        self,
    ) -> pd.DataFrame:
        """
        Return Packaging records.
        """

        return self.packaging

    # ============================================================
    # Summary
    # ============================================================

    def summary(self) -> None:
        """
        Print dataset statistics.
        """

        logger.info("========================================")
        logger.info("Transactional Dataset Summary")
        logger.info("========================================")

        datasets = {

            "Work Orders": self.work_orders,

            "Executions": self.executions,

            "Serial Numbers": self.serial_numbers,

            "Press Operations": self.press_operations,

            "Test Results": self.test_results,

            "Material Scans": self.material_scans,

            "Packaging": self.packaging,

        }

        for name, df in datasets.items():

            rows = 0 if df is None else len(df)

            logger.info(
                "%-20s %8d",
                name,
                rows,
            )

        logger.info("========================================")