
PRESS_FORCE_SAMPLE_RATE_HZ = 100

FORCE_CURVE_POINTS = 500

MAX_PRESS_FORCE_KN = 250

MAX_DISPLACEMENT_MM = 80

BARCODE_PREFIX_WORK_ORDER = "WO"

BARCODE_PREFIX_SERIAL = "SN"

ERP_SYSTEM = "SAP S/4HANA"

MES_SYSTEM = "MES"

SCADA_SYSTEM = "WinCC"

IOT_DEVICE = "Digiforce 9307"
